from enum import Enum


class LengthUnit(Enum):
    CAP = "cap"
    CH = "ch"
    CM = "cm"
    DVB = "dvb"
    DVH = "dvh"
    DVI = "dvi"
    DVMAX = "dvmax"
    DVMIN = "dvmin"
    DVW = "dvw"
    EM = "em"
    EX = "ex"
    IC = "ic"
    IN = "in"
    LH = "lh"
    LVB = "lvb"
    LVH = "lvh"
    LVI = "lvi"
    LVMAX = "lvmax"
    LVMIN = "lvmin"
    LVW = "lvw"
    MM = "mm"
    PC = "pc"
    PT = "pt"
    PX = "px"
    Q = "q"
    RCAP = "rcap"
    RCH = "rch"
    REM = "rem"
    REX = "rex"
    RIC = "ric"
    RLH = "rlh"
    SVB = "svb"
    SVH = "svh"
    SVI = "svi"
    SVMAX = "svmax"
    SVMIN = "svmin"
    SVW = "svw"
    VB = "vb"
    VH = "vh"
    VI = "vi"
    VMAX = "vmax"
    VMIN = "vmin"
    VW = "vw"